#!/bin/sh

DEST=images

if test ! -d $DEST ; then
   mkdir $DEST
fi

for FRULE in rules/*.osm
do

   CMD="smrender -P 50x50 -i testdata.osm -r $FRULE -G -o $DEST/$(basename ${FRULE%%.osm}.png) 15E34.35:43N44.06:10000"
   echo $CMD
   $CMD

done

