#!/bin/sh

cat <<!
\noindent\begin{tabular}{p{0.49\textwidth}p{0.49\textwidth}}
!

n=0
for c in $(grep "int act_" ../src/*c | sed 's/.*act_\(.*\)_\(ini\|fini\|main\).*/\1/' | uniq |sort)
do
   cl=$(echo $c | sed 's/_/\\_/g')
   cr=sec:act-$(echo $c | sed 's/_/-/g')
#   echo "$c \\hyperref[$cr]{$cl, \\ref*{$cr}}"
   echo -n "\\hyperref[$cr]{$cl, \\\\ref*{$cr}} "

   if test $n -eq 0 ; then
      echo -n "& "
      n=1
   else
      echo "\\\\\\\\"
      n=0
   fi
done

echo "\\\\end{tabular}"
