#!/bin/sh

tmp=$(mktemp)

cat <<!
\noindent\begin{tabular}{p{0.49\textwidth}p{0.49\textwidth}}
!

grep "int act_" ../src/*c | sed 's/.*act_\(.*\)_\(ini\|fini\|main\).*/\1/' | uniq |sort >/$tmp
l=$(($(wc -l <$tmp) / 2))

n=0
i=0
for c in $(cat $tmp)
do
   i=$(($i + 1))
   cl=$(echo $c | sed 's/_/\\_/g')
   cr=sec:act-$(echo $c | sed 's/_/-/g')
   echo "\\hyperref[$cr]{$cl, \\\\ref*{$cr}}"
   echo

   if test $i -eq $l ; then
      echo "&"
   fi

done

echo "\\\\end{tabular}"
rm $tmp

